### ISSUE TITLE
Add part to download RPAs, if needed

### ISSUE THREAD

**Issue by alicerunsonfedora** [Sayo-nika/quickstart-travis#1]
Our mod has a `.gitignore` that doesn't upload the original DDLC RPAs to the repository, and for good reasons. It would be helpful if you included a part in your Travis config that downloads DDLC and copies those RPAs over if needed.

**Comment by sr229** [comment]
This is done via [setup.sh](https://github.com/Sayo-nika/quickstart-travis/blob/master/setup.sh) already, which is pulling from our public S3 storage from IBM.

Should you wish to have another resource to pull, just modify this shell script. However, if you want to use the vanilla base we provide, that's fine as well.
